import { Navigation } from './components/Navigation'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const links = [
  {
    label: 'Home',
    route: '/'
  },
  {
    label: 'About',
    route: '/about'
  },
  {
    label: 'Posts',
    route: '/posts'
  }
]

export default function RootLayout({ children }) {
  return (
    <html>
      {' '}
      <body className={inter.className}>
        <Navigation links={links} />
        {children}
      </body>
    </html>
  )
}
